export enum ROUTES {
  LOGIN = 'login',
  REGISTER_USER = 'nutzer-registrierung',
  REGISTER_ACCOUNT = 'account-registrierung',
  PASSWORD_FORGOTTEN = 'passwort-vergessen',
  PASSWORD_RESET = 'passwort-reset',
  IMPRINT = 'impressum',
  LEGAL = 'rechtliches',
  REGISTER_USER_FINISH = 'registrierung',
  PROFILE = 'profil',
  TENANT_PLANNER = 'planner',
  TENANT_MANAGEMENT = 'verwaltung',
  TENANT_EVENTS = 'events',
  HOME = 'home',
}
